version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:2.23.0-pg16
    container_name: timescaledb_pg16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: ${TZ:-UTC}
    ports:
      - "5432:5432"                # << внешний порт 5432, внутри 5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - hft_network

networks:
  hft_network:
    driver: bridge