version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:2.23.0-pg16
    container_name: timescaledb_pg16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: ${TZ:-UTC}
    ports:
      - "5432:5432"                # << внешний порт 5432, внутри 5432
    # volumes:
    #   - D:/timescaledb:/var/lib/postgresql/data #:TODO: change to relative path
    #   - ./initdb:/docker-entrypoint-initdb.d:ro
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - hft_network

  # ==================== Postgres Exporter (для Prometheus) ====================
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter-timescale
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_SOURCE_URI: "timescaledb:5432/${POSTGRES_DB:-postgres}?sslmode=disable"
      DATA_SOURCE_USER: ${POSTGRES_USER:?Set POSTGRES_USER in .env}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
    ports:
      - "9187:9187"  # Prometheus scrape port
    networks:
      - hft_network
    depends_on:
      timescaledb:
        condition: service_healthy

  # ==================== Node Exporter (Host Metrics) ====================
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter-timescale
    restart: unless-stopped
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    pid: host
    ports:
      - "9100:9100"  # Prometheus scrape port
    networks:
      - hft_network

networks:
  hft_network:
    driver: bridge
    name: hft_network

# networks:
#   hft_network:
#     external: true
#     name: hft_network